version: "3.8"

services:
  pathfinder-db:
    image: postgres:16.3
    container_name: pathfinder-db
    environment:
      POSTGRES_DB: pathfinder
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: freak
    volumes:
      - pathfinder-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pathfinder-db-data:
