version: "3.8"

services:
  pathfinder-db:
    image: postgres:16.3
    container_name: packed-db
    environment:
      POSTGRES_DB: packed
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: freak
    volumes:
      - packed-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  packed-db-data:
